-- MySQL Script generated by MySQL Workbench
-- ven. 19 juin 2020 13:08:11 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema checkpoint3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `checkpoint3` ;

-- -----------------------------------------------------
-- Schema checkpoint3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checkpoint3` DEFAULT CHARACTER SET utf8mb4 ;
USE `checkpoint3` ;

-- -----------------------------------------------------
-- Table `checkpoint3`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checkpoint3`.`playlist` ;

CREATE TABLE IF NOT EXISTS `checkpoint3`.`playlist` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NULL DEFAULT NULL,
  `genre` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `checkpoint3`.`track`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `checkpoint3`.`track` ;

CREATE TABLE IF NOT EXISTS `checkpoint3`.`track` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `playlist_id` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(128) NULL DEFAULT NULL,
  `artist` VARCHAR(128) NULL DEFAULT NULL,
  `album_picture` VARCHAR(256) NULL DEFAULT NULL,
  `youtube_url` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_playlist_id_idx` (`playlist_id` ASC),
  CONSTRAINT `fk_playlist_id`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `checkpoint3`.`playlist` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
