-- MySQL Script generated by MySQL Workbench
-- Thu Oct 22 10:23:46 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema checkpoint3_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema checkpoint3_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checkpoint3_db` DEFAULT CHARACTER SET utf8 ;
USE `checkpoint3_db` ;

-- -----------------------------------------------------
-- Table `checkpoint3_db`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint3_db`.`playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NULL,
  `genre` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `checkpoint3_db`.`track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checkpoint3_db`.`track` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(248) NULL,
  `artist` VARCHAR(128) NULL,
  `album_picture` VARCHAR(5000) NULL,
  `youtube_url` VARCHAR(5000) NULL,
  `playlist_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_track_playlist_idx` (`playlist_id` ASC) VISIBLE,
  CONSTRAINT `fk_track_playlist`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `checkpoint3_db`.`playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `checkpoint3_db`.`playlist`
-- -----------------------------------------------------
START TRANSACTION;
USE `checkpoint3_db`;
INSERT INTO `checkpoint3_db`.`playlist` (`id`, `title`, `genre`) VALUES (1, 'Cuba', 'Cubain');
INSERT INTO `checkpoint3_db`.`playlist` (`id`, `title`, `genre`) VALUES (2, 'Soirees', 'Electro');
INSERT INTO `checkpoint3_db`.`playlist` (`id`, `title`, `genre`) VALUES (3, 'Classics', 'Classique');
INSERT INTO `checkpoint3_db`.`playlist` (`id`, `title`, `genre`) VALUES (4, 'Funky groove', 'Funky');

COMMIT;


-- -----------------------------------------------------
-- Data for table `checkpoint3_db`.`track`
-- -----------------------------------------------------
START TRANSACTION;
USE `checkpoint3_db`;
INSERT INTO `checkpoint3_db`.`track` (`id`, `title`, `artist`, `album_picture`, `youtube_url`, `playlist_id`) VALUES (1, 'Do you September', 'Eartch , Wind & Fire', 'https://i.pinimg.com/originals/e9/0d/c6/e90dc69c1fbd16f29a8beffe0a03df3d.jpg', 'https://www.youtube.com/watch?v=Gs069dndIYk', 4);
INSERT INTO `checkpoint3_db`.`track` (`id`, `title`, `artist`, `album_picture`, `youtube_url`, `playlist_id`) VALUES (2, 'Celebration', 'Kool & The Gang', 'https://i.pinimg.com/originals/e9/0d/c6/e90dc69c1fbd16f29a8beffe0a03df3d.jpg', 'https://www.youtube.com/watch?v=3GwjfUFyY6M', 4);
INSERT INTO `checkpoint3_db`.`track` (`id`, `title`, `artist`, `album_picture`, `youtube_url`, `playlist_id`) VALUES (3, 'First Man', 'Justin Hurwitz', 'https://images-na.ssl-images-amazon.com/images/I/717Nj8RgSxL._SL1500_.jpg', 'https://www.youtube.com/watch?v=yC0XxySqWro', 3);
INSERT INTO `checkpoint3_db`.`track` (`id`, `title`, `artist`, `album_picture`, `youtube_url`, `playlist_id`) VALUES (4, 'Carmina Burana', 'Carl Orff', 'https://i.pinimg.com/originals/e9/0d/c6/e90dc69c1fbd16f29a8beffe0a03df3d.jpg', 'https://www.youtube.com/watch?v=GXFSK0ogeg4', 3);
INSERT INTO `checkpoint3_db`.`track` (`id`, `title`, `artist`, `album_picture`, `youtube_url`, `playlist_id`) VALUES (5, 'Memories', 'David Guetta', 'https://images-na.ssl-images-amazon.com/images/I/61Q5jvGpH0L._SX355_.jpg', 'https://www.youtube.com/watch?v=NUVCQXMUVnI', 2);
INSERT INTO `checkpoint3_db`.`track` (`id`, `title`, `artist`, `album_picture`, `youtube_url`, `playlist_id`) VALUES (6, 'No Stress', 'Laurent Wolf', 'https://images-na.ssl-images-amazon.com/images/I/51bYPkRx8pL.jpg', 'https://www.youtube.com/watch?v=Up1MzGUhQG0', 2);
INSERT INTO `checkpoint3_db`.`track` (`id`, `title`, `artist`, `album_picture`, `youtube_url`, `playlist_id`) VALUES (7, 'Chan Chan', 'Buena Vista Social Club', 'https://i.pinimg.com/originals/e9/0d/c6/e90dc69c1fbd16f29a8beffe0a03df3d.jpg', 'https://www.youtube.com/watch?v=o5cELP06Mik', 1);
INSERT INTO `checkpoint3_db`.`track` (`id`, `title`, `artist`, `album_picture`, `youtube_url`, `playlist_id`) VALUES (8, 'Congo To Cuba', 'Putumayo', 'https://i.pinimg.com/originals/e9/0d/c6/e90dc69c1fbd16f29a8beffe0a03df3d.jpg', 'https://www.youtube.com/watch?v=IPb60Xi8TG0', 1);

COMMIT;

